"""add authentication fields to users

Revision ID: 58a83be4b0a2
Revises: 805b7795b007
Create Date: 2026-06-23 16:56:29.874886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a83be4b0a2'
down_revision: Union[str, Sequence[str], None] = '805b7795b007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregar la columna como nullable (permitiendo NULL temporalmente)
    with op.batch_alter_table('users', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=True))
    
    # 2. Asignar un valor temporal a los registros existentes para que no queden con NULL
    op.execute("UPDATE users SET hashed_password = 'temporary_hash' WHERE hashed_password IS NULL")
    
    # 3. Ahora sí, convertir la columna a NOT NULL
    with op.batch_alter_table('users', recreate='always') as batch_op:
        batch_op.alter_column('hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
